"""followers logic added to user model

Revision ID: 1961a084a4b8
Revises: 295206c04c4c
Create Date: 2020-07-26 19:36:00.791574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1961a084a4b8'
down_revision = '295206c04c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
